version: '3.9'

volumes:
  node_modules:
  build:
services:
  app:
    build: .
    volumes:
      - node_modules:/app/assets/node_modules
      - build:/app/_build
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - BASE_URL=http://localhost:4000
      - DB_URL=postgres://postgres:postgres@db/url_shortener_dev
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
