version: '3'

volumes:
  node_modules:
  build:

services:
  app:
    build: .
    volumes:
      - node_modules:/app/assets/node_modules
      - build:/app/_build
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - BASE_URL=http://localhost:4000
      - DB_URL=postgres://postgres:postgres@postgres/url_shortener_dev
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
